services: 
  nginx:
    image: nginx:1.23
    ports:
      - "8080:80"
    volumes:
      - ./projectSrc:/var/www
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm

  php-fpm:
    image: fpm-8.3:psql
    volumes:
      - ./projectSrc:/var/www
    working_dir: /var/www

  postgres:
    container_name: db_postgres_lab
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=first # CHANGE PER PROIJECT
      - POSTGRES_PASSWORD=pgpwd
      - POSTGRES_USER=pguser
    volumes:
      - ./dataDir:/var/lib/postgresql/data:rw
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
